modLoader = "javafml"
loaderVersion = "[1,)"

license = "MIT"
[[mods]]
modId = "ferritecore"
version = "${file.jarVersion}"
displayName = "Ferrite Core"
authors = "malte0811"
description = '''
Reduces memory usage.
'''
logoFile = "logo.png"
[[dependencies.ferritecore]]
modId = "neoforge"
mandatory = true
versionRange = "[20.2.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.ferritecore]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,1.21)"
ordering = "NONE"
side = "BOTH"
